# Step 1: Use the official Golang image as a base
FROM golang:1.21.3

# Step 2: Set the working directory in the container
WORKDIR /app

# Step 3: Copy go module files
COPY go.mod go.sum ./

# Step 4: Download dependencies
RUN go mod download

# Step 5: Copy the entire contents of the current directory to the container
COPY . .

# Step 6: Build the Go application
RUN go build -o main

# Step 7: Expose the port on which your API will run
EXPOSE 8092

# Step 8: Command to run the executable
CMD ["./main"]
